variable "region" {}
variable "vpc_cidr" {}
variable "vpc_name" {}
variable "publicsubnet_cidr" {}
variable "privatesubnet_cidr" {}
variable "az" {}
variable "ami" {}
variable "key" {}
variable "env" {}